apiVersion: skaffold/v2beta29
kind: Config

build:
  local:
    push: false

  artifacts:
    - image: rnraju075/auth
      context: auth
      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: rnraju075/client
      context: client
      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: '**/*.{ts,tsx,js,jsx}'
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml